name: CrazyAuctionsPlus
authors:
- Author87668
- BadBones69
- TRCStudioDean
main: studio.trc.bukkit.crazyauctionsplus.Main
version: ${version}
api-version: 1.20
description: restart version of CrazyAuctionsPlus plugin.
depend:
  - Vault
softdepend:
  - LangUtils
commands:
    ca:
        description: Crazy Auctions Plus Main command.
        aliases: [cap, crazyauction, crazyauctions, crazyauctionsplus, crazyauctionsplusx]